### ISSUE TITLE
Maps incorrectly tracks trunk lines

### ISSUE THREAD

**Issue by JakeCooper** [JakeCooper/nwHack2015#1]
Maps may be tracking IPs and using that to set locations. I'm not sure what's happening though.

http://i.imgur.com/RHItkB8.png

Will need to look into the maps code. Showed the app to my boss and it apparently worked for him on sign in, though he's signed in as John D through Facebook, something we need to fix as well.

**Comment by hwkr** [comment]
Chrome uses multiple tools to figure out where you are including GPS and your IP. This seems more like a desktop issue.

**Comment by JakeCooper** [comment]
Not sure I follow, because when you drop a locale it gets the position correctly, just the initial position is messed up.

**Comment by ChrisHampu** [comment]
Its possible that the browser wasn't able to pinpoint your location quickly enough before it used it. This is kind of better now though since we don't pull the location until the user signs in again. I'm unable to reproduce this issue though. The new auth system works much better in general, along with location (we even make sure location is possible now).
Because we rely not on Maps but the browser to give us the location (HTML5 navigator), there's not much more we can do. Same with the fact that location is easily spoofed.
