### ISSUE TITLE
The message box allows injection

### ISSUE THREAD

**Issue by hwkr** [JakeCooper/nwHack2015#4]
Try typing html in the message box.

``` javascript
<script> alert("This shouldn't be allowed... :(\n I wish I couldn\'t inject")</script>
```

![image](https://cloud.githubusercontent.com/assets/6374090/6675942/8324b910-cbe1-11e4-978f-3e884b320ea1.png)

**Comment by ChrisHampu** [comment]
We need to to do server side escaping of messages. Not sure what node has build in for this purpose.

**Comment by hwkr** [comment]
This should happen server side, and ideally when we read it in.
This might be a long term goal though.

**Comment by ChrisHampu** [comment]
When a client send a message, it gets appended immediately to chat through jquery which is why I added local sanitation. And people won't be able to xss each other anymore either if everyone is filtering locally. Server sanitation probably wouldn't guarantee this. But if you want to find a node module for Escaping messages, we could do both layers :)
